name: dart_planet
description: A sample command-line application.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  drift: ^2.8.0
  html: ^0.15.4
  http: ^1.0.0
  http_parser: ^4.0.2
  intl: ^0.18.1
  logging: ^1.2.0
  path: ^1.8.3
  sanitize_html: ^2.0.0
  universal_feed: ^0.4.0
  windows1251: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.8.0
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.0.0
